version: "3.9"

services:
  post-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: post-service
    working_dir: /app
    volumes:
      - ./build/libs/post-service-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8004:8004"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

    command: ["java", "-jar", "app.jar"]
    depends_on:
      - discovery-server
      - kafka

  discovery-server:
    image: discovery-server-discovery-service:latest
    ports:
      - "8761:8761"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
