server:
  port: 8004
  error:
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: post-service

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@instagram.ohyxk9x.mongodb.net/post_service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
