server:
  port: 8004
  error:
    include-stacktrace: never

spring:
  application:
    name: post-service

  data:
    mongodb:
      uri: mongodb+srv://martix_de_lavi:3ckxJ6UaLmWnmvk1@instagram.ohyxk9x.mongodb.net/post_service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

aws:
  region: eu-north-1
  s3:
    bucket: user-profile-avatars-martix-instagram
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

springdoc:
  api-docs:
    path: /post-service/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method