server:
  port: 8009

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://postgres-payment:5432/Instagram_Payment_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-service

stripe:
  api-secret-key: ${STRIPE_API_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
  webhook-key: ${STRIPE_WEBHOOK_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
