services:
  chat-service:
    image: eclipse-temurin:21-jre-alpine
    container_name: chat-service
    working_dir: /app
    volumes:
      - ./build/libs/chat-service-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./application-prod.yaml:/app/config/application-prod.yaml
    ports:
      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    command: ["java", "-jar", "app.jar"]
