server:
  port: 8002
  error:
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: profile-service

  datasource:
    url: jdbc:postgresql://postgres-user:5432/Instagram_User_Data_Management_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: profile-service
  data:
    redis:
      host: redis
      port: 6379
      password: redispass

  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
