server:
  port: 8002
  error:
    include-stacktrace: never

spring:
  application:
    name: profile-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.web.multipart: DEBUG
      org.springframework.http.converter: DEBUG
      org.springframework.beans.factory: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

aws:
  region: eu-north-1
  s3:
    bucket: user-profile-avatars-martix-instagram
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}