server:
  port: 8012
  error:
    include-stacktrace: never

spring:
  application:
    name: feed-service


eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method