server:
  port: 8005
  error:
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: comments-service

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@instagram.ohyxk9x.mongodb.net/comments_service

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
