server:
  port: 8011
  error:
    include-stacktrace: never

spring:
  application:
    name: calls-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-calls:5432/Instagram_Calls_Service

  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method