server:
  port: 8010
  error:
    include-stacktrace: never

spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@instagram.ohyxk9x.mongodb.net/chat-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method