server:
  port: 8000

spring:
  application:
    name: user-data-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Instagram_User_Data_Management_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-data-management-service

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

topics:
  authentication-service:
    user-management-service:
      consumer:
        registration: registration
        authentication: authentication
      producer:
            authentication: authentication-answer

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method