services:
  calls-service:
    image: eclipse-temurin:21-jre-alpine
    working_dir: /app
    volumes:
      - ./build/libs:/app
    command: ["java", "-jar", "calls-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8011:8011"
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/Instagram_Calls_Service
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 28859013
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: Instagram_Calls_Service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
