server:
  port: 8006
  error:
    include-stacktrace: never

spring:
  application:
    name: like-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-like:5432/Instagram_Like_Service

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelo-master.yml

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: like-service


eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui
    operations-sorter: method